Update docker-container-registry.yml

diff --git a/.github/workflows/docker-container-registry.yml b/.github/workflows/docker-container-registry.yml
--- a/.github/workflows/docker-container-registry.yml
+++ b/.github/workflows/docker-container-registry.yml
@@ -2,12 +2,16 @@ name: Build and push Docker Image to GitHub Container Registry
 
 on:
 #for manual trigger, will be change
- # workflow_dispatch:
+  workflow_dispatch:
+   inputs:
+    version:
+     description: 'Tag version'
+     required: true
 
  #for automatic trigger on version change
   push:
     tags:
-      - '*'
+       - 'v*.*.*'
 
 jobs:
   push_to_registry:
@@ -29,11 +33,26 @@ jobs:
         #password: ${{ secrets.GITHUB_TOKEN }}
         password: ${{secrets.GIT_PAT}}
 
-    - name: Get version tag
-      id: get_tag
-      #extract the last part of the GITHUB_REF
-      #the output from echo is redirected to the GITHUB_ENV file
-      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
+    # - name: Get version tag
+    #   id: get_tag
+    #   #extract the last part of the GITHUB_REF
+    #   #the output from echo is redirected to the GITHUB_ENV file
+    #   run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
+    
+    - name: Determine trigger type
+      id: determine-trigger
+      run: |
+        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+          echo "TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
+        else
+          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
+
+    - name: Validate version format
+      run: |
+        if [[ ! "${{ env.TAG }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid version format. Expected format: vX.X.X"
+          exit 1
+        fi
 
     - name: Build and push Docker image
       uses: docker/build-push-action@v5
